### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MisterNickyAlex** [devapple/yalu103#15]
Can somebody please explain me how this method works?

**Comment by fluffy66** [comment]
It doesn't its fake Stay away or you might find yourself at home depot

**Comment by MisterNickyAlex** [comment]
I'm sorry but i'm a lijtle bit new, but what is home depot?

**Comment by MisterNickyAlex** [comment]
Little*

**Comment by fluffy66** [comment]
its supposed to be Yalu 103 jailbreak not home depot....

**Comment by fluffy66** [comment]
like I said its fake there is no JB for ios 10.3 yet. We have to wait.

**Comment by MisterNickyAlex** [comment]
Well thats a sad story for us bro

**Comment by fluffy66** [comment]
Yeah man it sucks! I've been waiting a while now for a Jailbreak.

**Comment by MisterNickyAlex** [comment]
Than i think we need to wait a little bit longer

**Comment by devapple** [comment]
Yalu103 and home depot are totally different. Someone created a fake IPA. You can compile my project and fine no Home Depot. Because it's not apart of this project.
