### ISSUE TITLE
B1 needs to be released as soon as possible 

### ISSUE THREAD

**Issue by laxmanbhusal22** [devapple/yalu103#2]
B4 of iOS 10.3 is already out

**Comment by ZPCigaars** [comment]
Hope they are working on it though

**Comment by king4q** [comment]
Yes get this beta released very very soon please if beta 4 is out and the build number is as short as it is then IOS 10.3 is about to become public and released and the betas won't be signed anymore

**Comment by ZPCigaars** [comment]
Yeah probably there would be two more betas and public release will be there for iOS 10.3

**Comment by devapple** [comment]
I have updated, and added support for beta 4 (14E5260b) only firmware for now
